### ISSUE TITLE
About calculating "accuracy_class" in the "train/train_val.prototxt"

### ISSUE THREAD

**Issue by rockstone533** [ShapeNet/RenderForCNN#2]
Why shall we compute "accuracy_class" by the bottom layer be the same "label_class"?

refer to the code in the train/train_val.prototxt:

```
layers {
  name: "accuracy_class"
  type: ACCURACY
  bottom: "label_class"
  bottom: "label_class"
  top: "accuracy_class"
}
```

**Comment by charlesq34** [comment]
we can use SilenceLayer as well - it just prevents label_class to be printed in the log file, since it hasn't been used anywhere else.
