### ISSUE TITLE
ImportError: No module named lmdb

### ISSUE THREAD

**Issue by Shine41** [ShapeNet/RenderForCNN#4]
I'm trying to use the **off-the-shelf viewpoint estimator**, but when I do "python run_demo.py", I get the following:

Traceback (most recent call last):
  File "run_demo.py", line 13, in <module>
    from evaluation_helper import viewpoint
  File "/home/ying/Desktop/RenderForCNN/view_estimation/evaluation_helper.py", line 14, in <module>
    from caffe_utils import *
  File "/home/ying/Desktop/RenderForCNN/view_estimation/caffe_utils.py", line 3, in <module>
    import lmdb
ImportError: No module named lmdb

This confused me as **I did install lmdb** before installing caffe, and of course I have tried re-installing lmdb but still cannot fix the error above. I'm sure the prerequisites are done and the paths are set. What can I do to fix this problem?

Sorry for this naive question, as I'm quite new to this, thank you in advance : )

**Comment by charlesq34** [comment]
What happens if you run
$ python

> import lmdb

and in the view_estimation folder

$ python

> import caffe_utils

**Comment by Shine41** [comment]
@charlesq34 Thanks for your help! I'm able to import lmdb after running **pip install lmdb** rather than **apt-get install liblmdb-dev**, though I don't truly figure out the reason : )
